In [1]:
import numpy as np

In [2]:
# как создать матрицу?

In [3]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

In [4]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# размер матрицы
np.shape(A)

(4, 3)

In [6]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [7]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [8]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

[[1 2 3]] (1, 3)


In [9]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


In [10]:
# создание специальных матриц

In [11]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# матрица единиц
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [16]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

In [17]:
A

array([[1, 1],
       [2, 3],
       [4, 5]])

In [18]:
B

array([[ 1, -1],
       [-2,  3],
       [ 4, -5]])

In [19]:
A+B

array([[2, 0],
       [0, 6],
       [8, 0]])

In [20]:
B+A

array([[2, 0],
       [0, 6],
       [8, 0]])

In [21]:
A-B

array([[ 0,  2],
       [ 4,  0],
       [ 0, 10]])

In [22]:
2*A

array([[ 2,  2],
       [ 4,  6],
       [ 8, 10]])

In [23]:
A.T

array([[1, 2, 4],
       [1, 3, 5]])

In [24]:
# как транспонировать вектор?
x=np.array([1,2,3])
x.T

array([1, 2, 3])

In [25]:
x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))

[[1]
 [2]
 [3]]
(3, 1)


In [26]:
x_col.T

array([[1, 2, 3]])

In [27]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы numpy:

In [28]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

Составьте матрицу  доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [29]:
Inc=np.array([Husband_Income,Wife_Income,Mother_In_Law_Income]).T
print(Inc[0,0], Inc[1,1], Inc[2,2])

100 200 100


Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [30]:
Cons=np.array([Husband_Consumption,Wife_Consumption,Mother_In_Law_Consumption]).T
print(Cons[0,0], Cons[1,1], Cons[2,2])

50 80 140


Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте полученную ранее матрицу Inc, где доходы расположены по столбцам.

Выберите список элементов из первой строки этой матрицы (строки нумеруются с 1):

In [31]:
Inc_Tax=Inc*(1-0.13)
print(Inc_Tax[0])

[ 87.  130.5  78.3]


Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

In [32]:
P=Inc_Tax-Cons
print(P[2])

[ 61.8 -26.9 -53. ]
