In [1]:
import numpy as np

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[ 9, 11,  9],
       [ 5,  7,  9],
       [ 6,  7,  9]])

In [4]:
B

array([[ 1, -2, -2],
       [ 3, -2,  3],
       [ 0,  2,  1]])

In [5]:
# Поэлементное умножение
A*B

array([[  9, -22, -18],
       [ 15, -14,  27],
       [  0,  14,   9]])

In [6]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[ 42 -22  24]
 [ 26  -6  20]
 [ 27  -8  18]]


In [7]:
# Матричное умножение
np.dot(A,B)

array([[ 42, -22,  24],
       [ 26,  -6,  20],
       [ 27,  -8,  18]])

In [8]:
# Матричное умножение
A@B

array([[ 42, -22,  24],
       [ 26,  -6,  20],
       [ 27,  -8,  18]])

In [9]:
# Порядок умножения AB != BA
B@A

array([[-13, -17, -27],
       [ 35,  40,  36],
       [ 16,  21,  27]])

In [10]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 7  9  9 11  8]
 [ 9  5  5  9  6]
 [ 9  7  9 11  5]]
B:
 [[ 0 -1]
 [ 3  1]
 [ 3  0]
 [ 3  2]
 [-1  1]]


In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[79, 32],
       [51, 20],
       [76, 25]])

In [ ]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

In [15]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [16]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-1 -4 -4 -1]
 [ 0 -1  3  2]
 [-4 -1  2 -1]
 [-3 -4 -3  1]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-1 -8  0  1]
 [ 0 -2  0 -2]
 [-4 -2  0  1]
 [-3 -8  0 -1]]
DA:
 [[-1 -4 -4 -1]
 [ 0 -2  6  4]
 [ 0  0  0  0]
 [ 3  4  3 -1]]


In [17]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [ ]:
b@A

In [19]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [20]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [21]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [22]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [23]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

Даны матрица A и вектор х:

In [24]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

Найдите произведение матрицы A и вектора х в том порядке, в котором их можно умножить.

In [25]:
print(A@x)

[26 30]


In [26]:
#Даны две матрицы:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

Найдите произведение матриц A и B в том порядке, в котором их можно умножить.

In [27]:
C=B@A
print(C[0,3])

14


In [28]:
#Дана система векторов:

x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

Составьте матрицу A, расположив векторы x ,y ,z в строках. Найдите матрицу Грама G (матрицу скалярных произведений столбцов матрицы A ) системы векторов x ,y ,z.

In [29]:
A = np.array([x, y, z])
print(A.T@A)

[[ 6  3  0  2  4]
 [ 3  6  0  1  8]
 [ 0  0  3 -1  4]
 [ 2  1 -1  1  0]
 [ 4  8  4  0 16]]


В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [31]:
import pandas as pd
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию.

Вектор комиссий: com = np.array([0.2, 0.2, 0.3, 0.1, 0.1]).

Выберите координаты вектора прибыли салона:

In [32]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [33]:
P = Price_DF.values
C = Count_DF.values
salon_inc = (P*C)@(com)
print(salon_inc)

[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


Найдите вектор прибыли стилистов.

Выберите координаты полученного вектора:

In [34]:
P = Price_DF.values
C = Count_DF.values
styl_inc = (P*C)@(np.ones(5)-com)
print(styl_inc)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]
